exclude: ["TODO", "Makefile", "README.md"]
encoding: "utf-8"
timezone: "America/New_York"
defaults:
  -
    scope:
      path: ""
    values:
      pimg: "/portfolio/images/"
  -
    scope:
      path: "portfolio"
    values:
      layout: "default"
      type: "portfolio"
