"Lenovo Thinkpad E420":
  os: "Debian Jessie"
  desktop: "[cinnamon](http://cinnamon.linuxmint.com/)"
  editor: "vim"
  shell: "zsh"
  multiplexer: "tmux"
  configs: "[dotfiles](https://github.com/glentakahashi/dotfiles)"
  browser: "chrome"
"Custom PC":
  os: "Windows 7 Ultimate"
  photos: "lightroom"
"Personal":
  podcasts: "Freakonomics, Planet Money, 99% Invisible, NPR, Motley Fool Answers"
  books: "The Design of Everyday Things, Thinking Fast and Slow"
