"Macbook Pro 15 in.":
  editor: "vim"
  shell: "zsh"
  multiplexer: "tmux"
  configs: "[dotfiles](https://github.com/glentakahashi/dotfiles)"
  browser: "chrome"
  passwords: "1Password"
  finances: "YNAB 4"
"Personal":
  podcasts: "Freakonomics, Planet Money, 99% Invisible, NPR, Motley Fool Answers"
  books: "The Design of Everyday Things, Thinking Fast and Slow"
  periodicals: "The Economist, Wall Street Journal, New York Times"
