"Lenovo Thinkpad E420":
  os: "Debian Testing"
  "window manager": "[cinnamon](http://cinnamon.linuxmint.com/)"
  editor: "vim"
  shell: "zsh"
  terminalstuff: "tmux"
  browser: "chrome"
"Custom PC":
  os: "Windows 7 Ultimate"
  photos: "lightroom"
"glentaka.com":
  backend: "jekyll"
"Personal":
  music: "spotify"
  games: "CSGO, Dota 2"
  podcasts: "Freakonomics, Planet Money, 99% Invisible"
  books: "The Singularity Is Near"
